apiVersion: v1
entries:
  node-check-operator:
  - apiVersion: v2
    appVersion: 1.0.7
    created: "2025-11-21T09:47:08.229116+01:00"
    description: Helm chart to deploy the Node Check Operator and console plugin
    digest: 25de47022c50d45d119cb5e0db4a0ee29492cf067d753271b9dc8fb367f902f1
    keywords:
    - node
    - observability
    - openshift
    - kubernetes
    maintainers:
    - email: example@example.com
      name: Node Check Operator
    name: node-check-operator
    sources:
    - https://github.com/albertofilice/node-check-operator
    type: application
    urls:
    - https://albertofilice.github.io/node-check-operator/charts/node-check-operator-1.0.7.tgz
    version: 1.0.7
generated: "2025-11-21T09:47:08.22879+01:00"
